modLoader="javafml" #mandatory
loaderVersion="[${forge_version_range},)" #mandatory
credits="ErrorMikey" #optional
authors="JEC Team" #optional
license="GNU GPL v3.0 (https://github.com/MichaelHillcox/JEC-Mod/blob/master/LICENSE)"
[[mods]]
    modId="jec"
    version="${version}"
    displayName="Just Enough Charactors"
    description="Just Enough Charactors."

[[dependencies.jec]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_range},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.jec]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version_range})"
    ordering="NONE"
    side="CLIENT"
